language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - sudo apt-get install -y libkrb5-dev
script:
  - grunt test
  - grunt test:coverage
services: mongodb
after_success:
  - coveralls
