language: node_js
node_js:
- 4.2.3
cache:
  directories:
  - node_modules
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- sudo apt-get install -y libkrb5-dev
- npm install -g bower grunt-cli
- bower install
script:
- grunt test
- grunt test:coverage
services: mongodb
after_success:
- grunt coveralls
- grunt build
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: git
  before_deploy:
  - echo 'ready?'
  - sed 'dist' .gitignore
  - modified .gitignore
  api_key:
    secure: GvUSaYCMDOMzXTTG137uOn8jgI/8SQuz5usEuOZZR+a7sAYnJ8dQv66gadPJDz7d65gM0jkMy9KC8gUSTKqosC3ZkpdikNiCltcm9siYbng9+quJSUJWpBBzn8q5WQ9MRNwldr5PIojTJldm8Js379u0t9V7NRJs/HbIgJbfQpff9eF0RkSioIh45tYUR8Rq5E7ceYNLRs6zq9nOrRzEHRXHWcVg2rAPPMnN0QOhwa7PgB+PjExyVzo4rzFrS4CrKm7E+mDlEw0K2eUEiXljlgfBf0Hy4yIG7aB5GjdZv8X2uzwbhbqfHqEqy9AoxZImAWIKnbLpwxrt15EdH5bXQFsOBqV8DG0AlXaC0Md+sjpo7EprwsgL/WX9DO/YW7RRElkcg/pzra+4NI0xutc4MxM0lmin4x374bHmBlPTASwieKaFQSFAzs5LCqB7LTGlN6Wx3eQvXZkladfQlLYHnQfsrVCFrn7cKyfW7ihx/rozhkfozSqJKWMt5NFD9SytCqlBv6z9svJlljrM8sSLaJvwis/Q/nmWbLFnFUNIAVhGKKXe19YMuHbkkauIymgTCdWJXv6nPoEf9pu/rMt/YJMA9MV7V9vpNNX+HJJZ4CMyAuZJzSfsyKI5Gvz/RbLdHXy23di5h9FLCAVplGiPo9YlTXbrpqbT7UvaAwRN4uA=
  app: notas-core
  on: master
