language: node_js
node_js:
  - 4.2.3
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - sudo apt-get install -y libkrb5-dev
  - npm install -g bower grunt-cli
  - bower install
script:
  - grunt test
  - grunt test:coverage
services: mongodb
after_success:
  - grunt coveralls
  - grunt build
before_deploy:
  - echo 'ready?'
  - cd dist
  - git init
  - git add -A
  - git config user.name Bernix01
  - git config user.email gbernal096@gmail.com
  - git commit -m "dist"
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: git
  api_key:
    secure: ANZoDY8VpaQFiIc5WPBgntICiGEFlYqtXRVP8FFQXVQk5lTdMGNWnqXxxhhKBMtM9TdR8YYJuwISt5wjz2f7ZfbyH63JmGwSGkD0fl/QiTkLBddDUvvsAUesvdWemGLO1h+vZfPeDZR0b8F82jyk5uTdRNfGYPT2f4Y+NMAnA33PVEEMsLdRqdx82rMzXjQmz2WOhCMUSjwOS2dveBQh3qtIokTcGDNSfyJ3oOMbW8vFjfDr2Aesx+jx+tH3JTSx8YhORavjr+l4HomneOeoCz4d0LQaQppc2D8hhRCv1lcX+cKKKSzNAMjkejlfqL7qgX5fzjau2SguBJX/uVszTFv3Blt9rVCvNqfqBksR2FfRQ3Xx0GZ92LEtrdt5mm9ejfdNeTm+D3KcJipOctgDiTPHjBQz/p7uUCkVAMxq6FCMC/rh+Kco5/CVKKINx0fSFx6asnKFqU2oYXYByC8tXn7hMAJG1QIVWBEy3RFvvXqeCIgAGv59SBCkl65zOAw7vwXpLqjY++1ylLNfiojKiZYebJ3Zfm6NUV95uMo8JyFczhfwY/j93npwGQRGOOElKnrC84ANELQrLAbDRMwyU2zwy9RbzW2C4rl/R5h1I4KICjAy6gcWRFfoAahjZbDRsKxwAWYGKswkTrkqLAwbDewOpiAtrrEPmsKosDSyQU8=
  app: notas-core
  on:
    branch: master
  run: "ls -al && cat .gitignore"
after_deploy: "echo 'done.' && ls -al"
